server.port=5007
spring.application.name=ward-service

spring.datasource.url=jdbc:mysql://localhost:3306/ward_db
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html

#######################################
# Eureka client configuration
########################################
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register this service with Eureka
eureka.client.register-with-eureka=true

# Fetch registry information
eureka.client.fetch-registry=true