# =====================
# BASIC CONFIG
# =====================
spring.application.name=api-gateway
server.port=8083

# ======================================================
# Eureka client configuration
# ======================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register this service with Eureka
eureka.client.register-with-eureka=true

# Fetch registry information
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

logging.level.org.springframework.cloud.gateway.route=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG


# ======================================================
# ROUTES CONFIGURATION
# ======================================================

# 1. AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2

# 2. NOTIFICATION SERVICE
spring.cloud.gateway.routes[1].id=notification-service
spring.cloud.gateway.routes[1].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/notifications/**
#spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2

# 3. DOCTOR SERVICE
spring.cloud.gateway.routes[2].id=doctor-service
spring.cloud.gateway.routes[2].uri=lb://DOCTOR-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/doctors/**
#spring.cloud.gateway.routes[2].filters[0]=StripPrefix=2

# 4. PATIENT SERVICE
spring.cloud.gateway.routes[3].id=patient-service
spring.cloud.gateway.routes[3].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/patients/**
#spring.cloud.gateway.routes[3].filters[0]=StripPrefix=2

# 5. SLOT BOOKING SERVICE
spring.cloud.gateway.routes[4].id=slotbooking-service
spring.cloud.gateway.routes[4].uri=lb://SLOTBOOKING-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/slots/**
#spring.cloud.gateway.routes[4].filters[0]=StripPrefix=2

# 6. WARD SERVICE
spring.cloud.gateway.routes[5].id=ward-service
spring.cloud.gateway.routes[5].uri=lb://WARD-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/wards/**
#spring.cloud.gateway.routes[5].filters[0]=StripPrefix=2

# 7. BILLING SERVICE
spring.cloud.gateway.routes[6].id=billing-service
spring.cloud.gateway.routes[6].uri=lb://BILLING-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/billing/**
#spring.cloud.gateway.routes[6].filters[0]=StripPrefix=2

# 8. AUDIT & COMPLIANCE SERVICE
spring.cloud.gateway.routes[7].id=Audit-Compliance
spring.cloud.gateway.routes[7].uri=lb://AUDIT-COMPLIANCE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/audit/**
#spring.cloud.gateway.routes[7].filters[0]=StripPrefix=2

# 9. APPOINTMENT SERVICE
spring.cloud.gateway.routes[8].id=appointment-service
spring.cloud.gateway.routes[8].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/appointments/**
#spring.cloud.gateway.routes[8].filters[0]=StripPrefix=2

# 10. ANALYTICS SERVICE
spring.cloud.gateway.routes[9].id=analytics-service
spring.cloud.gateway.routes[9].uri=lb://ANALYTICS-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/analytics/**
#spring.cloud.gateway.routes[9].filters[0]=StripPrefix=2