server.port=5010
spring.application.name=audit-service

# Database (Keep your new audit_db)
spring.datasource.url=jdbc:mysql://localhost:3306/audit_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=G@2004
spring.jpa.hibernate.ddl-auto=update

# --- CRITICAL FIX FOR THE ERROR ---
# Tell the server NOT to register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# This ensures the server context doesn't time out waiting for a response
eureka.server.wait-time-in-ms-when-sync-empty=0